//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIMS {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABIMS.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domaine d&apos;activité.
        /// </summary>
        internal static string strActivityDomain {
            get {
                return ResourceManager.GetString("strActivityDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un client.
        /// </summary>
        internal static string strAddClient {
            get {
                return ResourceManager.GetString("strAddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter les clients.
        /// </summary>
        internal static string strAddClients {
            get {
                return ResourceManager.GetString("strAddClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter contact.
        /// </summary>
        internal static string strAddContact {
            get {
                return ResourceManager.GetString("strAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        internal static string strAdress {
            get {
                return ResourceManager.GetString("strAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler la création.
        /// </summary>
        internal static string strCancelCreation {
            get {
                return ResourceManager.GetString("strCancelCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler les modifications.
        /// </summary>
        internal static string strCancelModification {
            get {
                return ResourceManager.GetString("strCancelModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client.
        /// </summary>
        internal static string strClient {
            get {
                return ResourceManager.GetString("strClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste de clients.
        /// </summary>
        internal static string strClientList {
            get {
                return ResourceManager.GetString("strClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion client.
        /// </summary>
        internal static string strClientMgt {
            get {
                return ResourceManager.GetString("strClientMgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer toutes les fenêtres.
        /// </summary>
        internal static string strCloseWindows {
            get {
                return ResourceManager.GetString("strCloseWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires.
        /// </summary>
        internal static string strComm {
            get {
                return ResourceManager.GetString("strComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        internal static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacts.
        /// </summary>
        internal static string strContacts {
            get {
                return ResourceManager.GetString("strContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer le client.
        /// </summary>
        internal static string strDeleteClient {
            get {
                return ResourceManager.GetString("strDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer les clients.
        /// </summary>
        internal static string strDeleteClients {
            get {
                return ResourceManager.GetString("strDeleteClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer le contact.
        /// </summary>
        internal static string strDeleteContact {
            get {
                return ResourceManager.GetString("strDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail.
        /// </summary>
        internal static string strDetail {
            get {
                return ResourceManager.GetString("strDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail Client.
        /// </summary>
        internal static string strDetailClient {
            get {
                return ResourceManager.GetString("strDetailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vider liste.
        /// </summary>
        internal static string strDropList {
            get {
                return ResourceManager.GetString("strDropList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string strFirsName {
            get {
                return ResourceManager.GetString("strFirsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonction.
        /// </summary>
        internal static string strFunction {
            get {
                return ResourceManager.GetString("strFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée d&apos;intervention.
        /// </summary>
        internal static string strInterventionDuration {
            get {
                return ResourceManager.GetString("strInterventionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Garder ouvert.
        /// </summary>
        internal static string strKeepOpen {
            get {
                return ResourceManager.GetString("strKeepOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste.
        /// </summary>
        internal static string strList {
            get {
                return ResourceManager.GetString("strList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification.
        /// </summary>
        internal static string strModification {
            get {
                return ResourceManager.GetString("strModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le contact.
        /// </summary>
        internal static string strModifyContact {
            get {
                return ResourceManager.GetString("strModifyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nature.
        /// </summary>
        internal static string strNature {
            get {
                return ResourceManager.GetString("strNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        internal static string strPhone {
            get {
                return ResourceManager.GetString("strPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet.
        /// </summary>
        internal static string strProject {
            get {
                return ResourceManager.GetString("strProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réouvrir le client.
        /// </summary>
        internal static string strReopenClient {
            get {
                return ResourceManager.GetString("strReopenClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chiffre d&apos;affaire.
        /// </summary>
        internal static string strSalesRevenu {
            get {
                return ResourceManager.GetString("strSalesRevenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir les termes de votre recherche.
        /// </summary>
        internal static string strSearchSentence {
            get {
                return ResourceManager.GetString("strSearchSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir les clients.
        /// </summary>
        internal static string strSeeClients {
            get {
                return ResourceManager.GetString("strSeeClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir la fiche après la création.
        /// </summary>
        internal static string strSeeTheSheet {
            get {
                return ResourceManager.GetString("strSeeTheSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher liste.
        /// </summary>
        internal static string strShowList {
            get {
                return ResourceManager.GetString("strShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raison sociale.
        /// </summary>
        internal static string strSocietyName {
            get {
                return ResourceManager.GetString("strSocietyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effectif.
        /// </summary>
        internal static string strStaff {
            get {
                return ResourceManager.GetString("strStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer le contact.
        /// </summary>
        internal static string strSupprimer {
            get {
                return ResourceManager.GetString("strSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ABIMS - .
        /// </summary>
        internal static string strTitle {
            get {
                return ResourceManager.GetString("strTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider la creation.
        /// </summary>
        internal static string strValidCreation {
            get {
                return ResourceManager.GetString("strValidCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider les modifications.
        /// </summary>
        internal static string strValidModification {
            get {
                return ResourceManager.GetString("strValidModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fenêtres.
        /// </summary>
        internal static string strWindows {
            get {
                return ResourceManager.GetString("strWindows", resourceCulture);
            }
        }
    }
}
