//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIMS {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABIMS.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Domaine d&apos;activité&quot;.
        /// </summary>
        internal static string strActivityDomain {
            get {
                return ResourceManager.GetString("strActivityDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Ajouter un client&quot;.
        /// </summary>
        internal static string strAddClient {
            get {
                return ResourceManager.GetString("strAddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Ajouter les clients&quot;.
        /// </summary>
        internal static string strAddClients {
            get {
                return ResourceManager.GetString("strAddClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Ajouter contact&quot;.
        /// </summary>
        internal static string strAddContact {
            get {
                return ResourceManager.GetString("strAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Adresse&quot;.
        /// </summary>
        internal static string strAdress {
            get {
                return ResourceManager.GetString("strAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Annuler la création&quot;.
        /// </summary>
        internal static string strCancelCreation {
            get {
                return ResourceManager.GetString("strCancelCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Annuler les modifications&quot;.
        /// </summary>
        internal static string strCancelModification {
            get {
                return ResourceManager.GetString("strCancelModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Client&quot;.
        /// </summary>
        internal static string strClient {
            get {
                return ResourceManager.GetString("strClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Liste de clients&quot;.
        /// </summary>
        internal static string strClientList {
            get {
                return ResourceManager.GetString("strClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Gestion client&quot;.
        /// </summary>
        internal static string strClientMgt {
            get {
                return ResourceManager.GetString("strClientMgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Fermer toutes les fenêtres&quot;.
        /// </summary>
        internal static string strCloseWindows {
            get {
                return ResourceManager.GetString("strCloseWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Commentaires&quot;.
        /// </summary>
        internal static string strComm {
            get {
                return ResourceManager.GetString("strComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Contact&quot;.
        /// </summary>
        internal static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Contacts&quot;.
        /// </summary>
        internal static string strContacts {
            get {
                return ResourceManager.GetString("strContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Supprimer le client&quot;.
        /// </summary>
        internal static string strDeleteClient {
            get {
                return ResourceManager.GetString("strDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Supprimer les clients&quot;.
        /// </summary>
        internal static string strDeleteClients {
            get {
                return ResourceManager.GetString("strDeleteClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Supprimer le contact&quot;.
        /// </summary>
        internal static string strDeleteContact {
            get {
                return ResourceManager.GetString("strDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Détail&quot;.
        /// </summary>
        internal static string strDetail {
            get {
                return ResourceManager.GetString("strDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Détail Client&quot;.
        /// </summary>
        internal static string strDetailClient {
            get {
                return ResourceManager.GetString("strDetailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Vider liste&quot;.
        /// </summary>
        internal static string strDropList {
            get {
                return ResourceManager.GetString("strDropList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Email&quot;.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Prénom&quot;.
        /// </summary>
        internal static string strFirsName {
            get {
                return ResourceManager.GetString("strFirsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Fonction&quot;.
        /// </summary>
        internal static string strFunction {
            get {
                return ResourceManager.GetString("strFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Durée d&apos;intervention&quot;.
        /// </summary>
        internal static string strInterventionDuration {
            get {
                return ResourceManager.GetString("strInterventionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Garder ouvert&quot;.
        /// </summary>
        internal static string strKeepOpen {
            get {
                return ResourceManager.GetString("strKeepOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Liste&quot;.
        /// </summary>
        internal static string strList {
            get {
                return ResourceManager.GetString("strList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Modification&quot;.
        /// </summary>
        internal static string strModification {
            get {
                return ResourceManager.GetString("strModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Modifier le contact&quot;.
        /// </summary>
        internal static string strModifyContact {
            get {
                return ResourceManager.GetString("strModifyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Nom&quot;.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Nature&quot;.
        /// </summary>
        internal static string strNature {
            get {
                return ResourceManager.GetString("strNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Téléphone&quot;.
        /// </summary>
        internal static string strPhone {
            get {
                return ResourceManager.GetString("strPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Projet&quot;.
        /// </summary>
        internal static string strProject {
            get {
                return ResourceManager.GetString("strProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Réouvrir le client&quot;.
        /// </summary>
        internal static string strReopenClient {
            get {
                return ResourceManager.GetString("strReopenClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Chiffre d&apos;affaire&quot;.
        /// </summary>
        internal static string strSalesRevenu {
            get {
                return ResourceManager.GetString("strSalesRevenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Rechercher&quot;.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Saisir les termes de votre recherche&quot;.
        /// </summary>
        internal static string strSearchSentence {
            get {
                return ResourceManager.GetString("strSearchSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Voir les clients&quot;.
        /// </summary>
        internal static string strSeeClients {
            get {
                return ResourceManager.GetString("strSeeClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Voir la fiche après la création&quot;.
        /// </summary>
        internal static string strSeeTheSheet {
            get {
                return ResourceManager.GetString("strSeeTheSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Afficher liste&quot;.
        /// </summary>
        internal static string strShowList {
            get {
                return ResourceManager.GetString("strShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Raison sociale&quot;.
        /// </summary>
        internal static string strSocietyName {
            get {
                return ResourceManager.GetString("strSocietyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Effectif&quot;.
        /// </summary>
        internal static string strStaff {
            get {
                return ResourceManager.GetString("strStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;le contact&quot;.
        /// </summary>
        internal static string strSupprimer {
            get {
                return ResourceManager.GetString("strSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;ABIMS - &quot;.
        /// </summary>
        internal static string strTitle {
            get {
                return ResourceManager.GetString("strTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Type&quot;.
        /// </summary>
        internal static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Valider la creation&quot;.
        /// </summary>
        internal static string strValidCreation {
            get {
                return ResourceManager.GetString("strValidCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Valider les modifications&quot;.
        /// </summary>
        internal static string strValidModification {
            get {
                return ResourceManager.GetString("strValidModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Fenêtres&quot;.
        /// </summary>
        internal static string strWindows {
            get {
                return ResourceManager.GetString("strWindows", resourceCulture);
            }
        }
    }
}
